package com.example.nutritrack.presentation.meal

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.nutritrack.data.repository.FirestoreMealRepository
import com.example.nutritrack.domain.model.Meal
import com.example.nutritrack.domain.model.MealType
import com.example.nutritrack.domain.model.UiState
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import java.util.Date

class MealViewModel(
    private val firestoreMealRepository: FirestoreMealRepository
) : ViewModel() {

    private val _addMealState = MutableStateFlow<AddMealUiState>(AddMealUiState())
    val addMealState: StateFlow<AddMealUiState> = _addMealState.asStateFlow()

    private val _saveMealState = MutableStateFlow<UiState<String>>(UiState.Idle)
    val saveMealState: StateFlow<UiState<String>> = _saveMealState.asStateFlow()

    private val _deleteMealState = MutableStateFlow<UiState<Unit>>(UiState.Idle)
    val deleteMealState: StateFlow<UiState<Unit>> = _deleteMealState.asStateFlow()

    /**
     * Update food name
     */
    fun updateFoodName(name: String) {
        _addMealState.value = _addMealState.value.copy(foodName = name)
    }

    /**
     * Update meal type
     */
    fun updateMealType(mealType: MealType) {
        _addMealState.value = _addMealState.value.copy(mealType = mealType)
    }

    /**
     * Update serving size
     */
    fun updateServingSize(servingSize: String) {
        _addMealState.value = _addMealState.value.copy(servingSize = servingSize)
    }

    /**
     * Update quantity
     */
    fun updateQuantity(quantity: Float) {
        _addMealState.value = _addMealState.value.copy(quantity = quantity)
        recalculateNutrition()
    }

    /**
     * Update calories (per serving)
     */
    fun updateCaloriesPerServing(calories: Int) {
        _addMealState.value = _addMealState.value.copy(caloriesPerServing = calories)
        recalculateNutrition()
    }

    /**
     * Update protein (per serving)
     */
    fun updateProteinPerServing(protein: Int) {
        _addMealState.value = _addMealState.value.copy(proteinPerServing = protein)
        recalculateNutrition()
    }

    /**
     * Update carbs (per serving)
     */
    fun updateCarbsPerServing(carbs: Int) {
        _addMealState.value = _addMealState.value.copy(carbsPerServing = carbs)
        recalculateNutrition()
    }

    /**
     * Update fat (per serving)
     */
    fun updateFatPerServing(fat: Int) {
        _addMealState.value = _addMealState.value.copy(fatPerServing = fat)
        recalculateNutrition()
    }

    /**
     * Recalculate total nutrition based on quantity
     */
    private fun recalculateNutrition() {
        val state = _addMealState.value
        _addMealState.value = state.copy(
            totalCalories = (state.caloriesPerServing * state.quantity).toInt(),
            totalProtein = (state.proteinPerServing * state.quantity).toInt(),
            totalCarbs = (state.carbsPerServing * state.quantity).toInt(),
            totalFat = (state.fatPerServing * state.quantity).toInt()
        )
    }

    /**
     * Set food from database (when user selects from search)
     */
    fun setFoodFromDatabase(
        foodId: String,
        foodName: String,
        servingSize: String,
        calories: Int,
        protein: Int,
        carbs: Int,
        fat: Int
    ) {
        _addMealState.value = AddMealUiState(
            foodId = foodId,
            foodName = foodName,
            servingSize = servingSize,
            quantity = 1f,
            caloriesPerServing = calories,
            proteinPerServing = protein,
            carbsPerServing = carbs,
            fatPerServing = fat,
            totalCalories = calories,
            totalProtein = protein,
            totalCarbs = carbs,
            totalFat = fat
        )
    }

    /**
     * Save meal to Firestore
     */
    fun saveMeal(userId: String) {
        val state = _addMealState.value

        // Validation
        if (state.foodName.isBlank()) {
            _saveMealState.value = UiState.Error("Food name is required")
            return
        }
        if (state.quantity <= 0) {
            _saveMealState.value = UiState.Error("Quantity must be greater than 0")
            return
        }

        _saveMealState.value = UiState.Loading

        viewModelScope.launch {
            val meal = Meal(
                id = "", // Will be generated by Firestore
                foodId = state.foodId,
                foodName = state.foodName,
                mealType = state.mealType,
                servingSize = state.servingSize,
                quantity = state.quantity,
                calories = state.totalCalories,
                protein = state.totalProtein,
                carbs = state.totalCarbs,
                fat = state.totalFat,
                timestamp = Date()
            )

            val result = firestoreMealRepository.addMeal(userId, meal)

            _saveMealState.value = if (result.isSuccess) {
                UiState.Success(result.getOrNull() ?: "")
            } else {
                UiState.Error(result.exceptionOrNull()?.message ?: "Failed to save meal")
            }
        }
    }

    /**
     * Update existing meal
     */
    fun updateMeal(userId: String, mealId: String) {
        val state = _addMealState.value

        // Validation
        if (state.foodName.isBlank()) {
            _saveMealState.value = UiState.Error("Food name is required")
            return
        }

        _saveMealState.value = UiState.Loading

        viewModelScope.launch {
            val meal = Meal(
                id = mealId,
                foodId = state.foodId,
                foodName = state.foodName,
                mealType = state.mealType,
                servingSize = state.servingSize,
                quantity = state.quantity,
                calories = state.totalCalories,
                protein = state.totalProtein,
                carbs = state.totalCarbs,
                fat = state.totalFat,
                timestamp = Date()
            )

            val result = firestoreMealRepository.updateMeal(userId, meal)

            _saveMealState.value = if (result.isSuccess) {
                UiState.Success(mealId)
            } else {
                UiState.Error(result.exceptionOrNull()?.message ?: "Failed to update meal")
            }
        }
    }

    /**
     * Delete meal
     */
    fun deleteMeal(userId: String, mealId: String, timestamp: Date) {
        _deleteMealState.value = UiState.Loading

        viewModelScope.launch {
            val result = firestoreMealRepository.deleteMeal(userId, mealId, timestamp)

            _deleteMealState.value = if (result.isSuccess) {
                UiState.Success(Unit)
            } else {
                UiState.Error(result.exceptionOrNull()?.message ?: "Failed to delete meal")
            }
        }
    }

    /**
     * Load meal for editing
     */
    fun loadMealForEdit(meal: Meal) {
        _addMealState.value = AddMealUiState(
            foodId = meal.foodId,
            foodName = meal.foodName,
            mealType = meal.mealType,
            servingSize = meal.servingSize,
            quantity = meal.quantity,
            caloriesPerServing = (meal.calories / meal.quantity).toInt(),
            proteinPerServing = (meal.protein / meal.quantity).toInt(),
            carbsPerServing = (meal.carbs / meal.quantity).toInt(),
            fatPerServing = (meal.fat / meal.quantity).toInt(),
            totalCalories = meal.calories,
            totalProtein = meal.protein,
            totalCarbs = meal.carbs,
            totalFat = meal.fat
        )
    }

    /**
     * Reset form
     */
    fun resetForm() {
        _addMealState.value = AddMealUiState()
        _saveMealState.value = UiState.Idle
    }

    /**
     * Reset save state
     */
    fun resetSaveState() {
        _saveMealState.value = UiState.Idle
    }

    /**
     * Reset delete state
     */
    fun resetDeleteState() {
        _deleteMealState.value = UiState.Idle
    }
}

/**
 * UI State for Add/Edit Meal Screen
 */
data class AddMealUiState(
    val foodId: String = "",
    val foodName: String = "",
    val mealType: MealType = MealType.BREAKFAST,
    val servingSize: String = "100g",
    val quantity: Float = 1f,
    val caloriesPerServing: Int = 0,
    val proteinPerServing: Int = 0,
    val carbsPerServing: Int = 0,
    val fatPerServing: Int = 0,
    val totalCalories: Int = 0,
    val totalProtein: Int = 0,
    val totalCarbs: Int = 0,
    val totalFat: Int = 0
)
